version: '3.8'
services:
  fastapi-app:
    image: prashrex/html-front:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    stdin_open: true
    networks:
      - express_nw

  watchtower:
    image: containrrr/watchtower
    command: --interval 30 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
    
networks:
express_nw:
  driver: bridge
